### ISSUE TITLE
Demo generate errors

### ISSUE THREAD

**Issue by prpr2770** [riswords/quiche#2]
I obtained the following errors when testing out the demo files. 

Testing `egraphs_demo.py`: 
```
$ python ./egraphs_demo.py 
PYTHON VERSION:  (3, 9)
PYTHON VERSION:  (3, 9)
PYTHON VERSION:  (3, 9)
PYTHON VERSION:  (3, 9)
Traceback (most recent call last):
  File "./egraphs_demo.py", line 33, in <module>
    main()
  File "./egraphs_demo.py", line 19, in main
    egraph.apply_rules(rules)
AttributeError: 'EGraph' object has no attribute 'apply_rules'
```
Testing `demo.py`: 
```
$ python demo.py 
PYTHON VERSION:  (3, 9)
PYTHON VERSION:  (3, 9)
(<class 'ast.Module'> (<class 'quiche.pyast.pal.pal_block.StmtBlock'> (<class 'ast.FunctionDef'> (<class 'quiche.pyast.pal.pal_block.PALIdentifier'> newton) (<class 'ast.arguments'> <class 'quiche.pyast.pal.pal_block.ArgBlock'> (<class 'quiche.pyast.pal.pal_block.ArgBlock'> (<class 'ast.arg'> (<class 'quiche.pyast.pal.pal_block.PALIdentifier'> number) <class 'NoneType'> <class 'NoneType'>)) <class 'NoneType'> <class 'quiche.pyast.pal.pal_block.ArgBlock'> <class 'quiche.pyast.pal.pal_block.ExprBlock'> <class 'NoneType'> <class 'quiche.pyast.pal.pal_block.ExprBlock'>) (<class 'quiche.pyast.pal.pal_block.StmtBlock'> (<class 'ast.Expr'> (<class 'ast.Constant'> 
    Newton's method for square root
     <class 'NoneType'>)) (<class 'ast.Assign'> (<class 'quiche.pyast.pal.pal_block.ExprBlock'> (<class 'ast.Name'> x <class 'ast.Store'>)) (<class 'ast.BinOp'> (<class 'ast.Name'> number <class 'ast.Load'>) <class 'ast.Div'> (<class 'ast.Constant'> <class 'int'> <class 'NoneType'>)) <class 'NoneType'>) (<class 'ast.While'> (<class 'ast.Constant'> <class 'bool'> <class 'NoneType'>) (<class 'quiche.pyast.pal.pal_block.StmtBlock'> (<class 'ast.Assign'> (<class 'quiche.pyast.pal.pal_block.ExprBlock'> (<class 'ast.Name'> y <class 'ast.Store'>)) (<class 'ast.BinOp'> (<class 'ast.BinOp'> (<class 'ast.Name'> x <class 'ast.Load'>) <class 'ast.Add'> (<class 'ast.BinOp'> (<class 'ast.Name'> number <class 'ast.Load'>) <class 'ast.Div'> (<class 'ast.Name'> x <class 'ast.Load'>))) <class 'ast.Div'> (<class 'ast.Constant'> <class 'int'> <class 'NoneType'>)) <class 'NoneType'>) (<class 'ast.If'> (<class 'ast.Compare'> (<class 'ast.Name'> y <class 'ast.Load'>) (<class 'quiche.pyast.pal.pal_block.CmpopBlock'> <class 'ast.Eq'>) (<class 'quiche.pyast.pal.pal_block.ExprBlock'> (<class 'ast.Name'> x <class 'ast.Load'>))) (<class 'quiche.pyast.pal.pal_block.StmtBlock'> (<class 'ast.Return'> (<class 'ast.Name'> y <class 'ast.Load'>))) <class 'quiche.pyast.pal.pal_block.StmtBlock'>) (<class 'ast.Assign'> (<class 'quiche.pyast.pal.pal_block.ExprBlock'> (<class 'ast.Name'> x <class 'ast.Store'>)) (<class 'ast.Name'> y <class 'ast.Load'>) <class 'NoneType'>)) <class 'quiche.pyast.pal.pal_block.StmtBlock'>)) <class 'quiche.pyast.pal.pal_block.ExprBlock'> <class 'NoneType'> <class 'NoneType'>)) <class 'quiche.pyast.pal.pal_block.TypeIgnoreBlock'>)
PYTHON VERSION:  (3, 9)
Traceback (most recent call last):
  File "./quiche/demo/demo.py", line 29, in <module>
    egraph.apply_rules([rewrite])
AttributeError: 'EGraph' object has no attribute 'apply_rules'
```

**Comment by riswords** [comment]
Demo code is functioning. Leaving this issue open until I get it properly under test.
